name: Test

 on: push
 jobs: 
     test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'

            - name: Install dependencies
              run: yarn

            - name: Clean
              run: yarn clean

            - name: Run tests
              run: yarn test

            - name: Create bundle
              run: yarn dist
